### ISSUE TITLE
Make psycopg2 an optional dependency

### ISSUE THREAD

**Issue by robinandeer** [ewels/MegaQC#1]
Postgresql is a pain in the *** to install on Mac.

Since it's not a hard dependency, would it not be nice if `psycopg2` was an optional dependency since it fails when Postgreql isn't install on your system?

Reference for optional dependencies:
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by ewels** [comment]
This is now done, as it's only present in the production installation requirements.
