### ISSUE TITLE
Python 3(.6) compatibility

### ISSUE THREAD

**Issue by remiolsen** [ewels/MegaQC#10]
A few inconsistencies with Python 3. Example in [megaqc/public/views.py](megaqc/public/views.py)

```python
from urllib import unquote_plus
# Should be
try:
    from urllib import unquote_plus
except ImportError:
    from urllib.parse import unquote_plus
```
I'm sure there's a few others.

Also, I suspect https://github.com/pallets/itsdangerous is not 3.6 compatible

**Comment by tsnowlan** [comment]
Co-opting this bug for a larger issue. It has been announced that Python 2.7 will not be maintained past Jan 1, 2020. This also includes security releases, and many major module maintainers ([pandas, ipython, matplotlib, etc.](http://python3statement.org/)) have pledged to stop support on or before that date as well.

I'll hopefully be able to work on this while getting MegaQC going internally here, but 2+3 compatibility for MultiQC and MegaQC might need to be a higher priority.

**Comment by tsnowlan** [comment]
sending a PR for this one soon

**Comment by tsnowlan** [comment]
This should be good to close :+1:
