### ISSUE TITLE
Providing pre-built JavaScript

### ISSUE THREAD

**Issue by TMiguelT** [ewels/MegaQC#106]
As per earlier discussion, we now have a build process for compiling the JavaScript, which adds an additional hurdle for people wanting to install MegaQC.

We could either:
* Keep it as is, meaning users now have to install `node` to compile the JS
* Add the compiled JS to source control
* Include pre-compiled JS to MegaQC *releases*

I prefer this latter approach because adding the compiled JS to source will muddy up the diffs, add redundancy, and increase the repo size. As it stands, this would be a manual release process, but later on we could add a release mechanism whereby we tag a commit, then the CI compiles the JS, makes a release, and attaches a zip file with the compiled JS to that release.

Oh, and we can also include this compiled JS in the pip package, which can also be automatically released using the CI. 

Thoughts?

**Comment by tsnowlan** [comment]
Including compiled JS with releases sounds best to me as well, though I'd say only once it can been done automatically by CI

**Comment by TMiguelT** [comment]
Oh, it turns out that we're already included the contents of the whole static directory in the Python packages (due to the `MANIFEST.in`), so enabling this should be as simple as getting the CI to build and deploy packages (to PyPI, and to Github releases). PR incoming.
