### ISSUE TITLE
Field selection on trends page

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MegaQC#112]
I'm seeing some issues with selecting fields to plot on the new trends page.

* First is the "select multiple" label, but then using a drop down list where you can only select one field
* Only the first 30 entries in `sample_data_type` are given (pagination issue?)
* The name displayed is the ugly compound name (`picard_insertSize__WIDTH_OF_99_PERCENT`) not the nice human readable one displayed in MultiQC

I had some initial problems getting the compiled javascript working, so unsure if this is an environmental issue. How's it look on your end @TMiguelT ?

**Comment by tsnowlan** [comment]
![Drop down field selection with ugly field names](https://user-images.githubusercontent.com/5105646/75140315-ed337880-56ee-11ea-84c5-9667cded4bea.png)

**Comment by TMiguelT** [comment]
Hmm, it certainly shouldn't be like that. "Select Multiple" might be out of date, because I removed the ability to plot multiple fields. And regarding the compound name, I thought they were being used even in the old version? If we have a function to prettify the field names I'll happily use it, though.

The actual display of the dropdown doesn't seem correct, though. Can you show me your browser console, and maybe explain how you compiled the JS? I started writing some dev docs over in #107 so I'm eager to hear any feedback about what documentation you need.

**Comment by tsnowlan** [comment]
Field listing on older trend analysis page (installed from master commit `1a0b6259`):

![Previous MegaQC version](https://user-images.githubusercontent.com/5105646/75141339-076e5600-56f1-11ea-838c-4b1bb69c1395.png)

**Comment by TMiguelT** [comment]
I believe I started the page with a goal of recreating that field selection box exactly in React, and decided a select dropdown was *significantly* less code, for effectively the same result. Once I fix up the field names and the other text, is it being a dropdown a deal-breaker for you? I can try to recreate the old form if you find it has significantly better usability.

**Comment by tsnowlan** [comment]
Initial problems I had were with getting webpack to work and silent failures (just blank page) when using old database schema. The PR gave the step as simply `webpack` or `webpack --production`, but webpack isn't an available executable when installing MegaQC packages via the local `npm install` route. The updates to the package.json with the runnable scripts in the PR simplify that, but at the time I had to take a look at the CI config to see how it was running. I've been using `npx webpack --mode production` to compile the js since then.

Console of the list element:

![plot_console](https://user-images.githubusercontent.com/5105646/75142411-4f8e7800-56f3-11ea-8cc4-350b0c823515.png)

**Comment by tsnowlan** [comment]
I don't know that multi-select is hard dealbreaker, but it's really helpful when looking at similar values.  Specifically all combinations of False Positive/False Negative/PASS/ALL/SNP/INDEL for control samples. That becomes a lot of individual plots if they must be separate.

**Comment by ewels** [comment]
Agree, it's definitely a dealbreaker. Looking for trends in multiple different metrics is the main thing that we use this page for (or at least it's equivalent in our older system)..

**Comment by TMiguelT** [comment]
Okay sorry about this. I've added some issues that should help me keep track of everything. I'll try to fix it asap.

Regarding Webpack, you're right, it would have to be run as `npx webpack` rather than `webpack`, but also the new scripts in #107 should solve this problem in a better way.

**Comment by TMiguelT** [comment]
Okay, I've got multi-series plotting back in, the better formatted names, as well as some updates from #101. Screenshot attached.

Any feedback from either of you while we're on this topic? Would you rather the old data type selection rather than a vanilla multi-select?

![image](https://user-images.githubusercontent.com/5019367/75417949-5d0f6080-5986-11ea-8aa9-313212ea1e4b.png)

**Comment by tsnowlan** [comment]
That looks good! Are the outlier detection and mean lines based on all the selected fields or per-field?

**Comment by TMiguelT** [comment]
Currently they're separate for each field, so if you select 3 fields, you'll get a mean line and shaded control limits for each field which doesn't really make sense, but you can switch them on and off.

**Comment by tsnowlan** [comment]
That should be good. It would be neat to have the option to have combined summary output, but it seems like it'd be complicated and it's not really necessary.

**Comment by TMiguelT** [comment]
What do you mean by combined summary?

**Comment by tsnowlan** [comment]
the median/outlier based on the data from all selected fields as opposed to per-field

**Comment by TMiguelT** [comment]
Oh, I suppose I could do that, but it wouldn't make sense in a lot of cases. If the data isn't comparable
