### ISSUE TITLE
Docker-compose deployment

### ISSUE THREAD

**Issue by TMiguelT** [ewels/MegaQC#123]
We should have a docker-compose file which allows easy deployment to a k8s cluster, AWS via fargate etc. Containers will include: 

* MegaQC, with gunicorn
* Nginx proxy
* Postgres

**Comment by TMiguelT** [comment]
Also hoping to add a CloudFormation script for AWS deployment. Unfortunately I can't re-use the compose file for this, because it should use Aurora Postgres which isn't a docker container.

**Comment by TMiguelT** [comment]
Also, we should be building docker images and pushing them to Docker Hub on publish.

**Comment by ewels** [comment]
I think we already are? https://hub.docker.com/r/ewels/megaqc

**Comment by TMiguelT** [comment]
Oh, gosh. I had no idea. That's not in the GitHub Actions CI, so how is that being published? Is it being run by Docker hub somehow?

**Comment by ewels** [comment]
Yeah, DockerHub has integration with GitHub so can trigger builds on events from that side. That's how I used to do it everywhere for a long time. The builds can take a long time on DockerHub though (eg. 8hrs+ on some pipelines, with most of that time it just sat in a queue waiting) so I'm slowly moving to building + pushing on GitHub Actions CI on other projects.

**Comment by ewels** [comment]
It's very easy to turn that automation off if we want to switch to a CI push - just let me know (I can also add you as a collaborator on the DockerHub repo).

**Comment by TMiguelT** [comment]
Hmm, interesting. Well I'll see how long it's taking and move it over to Actions if it's too slow. I wouldn't mind being added as a collaborator, it might matter at some point.

**Comment by ewels** [comment]
Sure - what's your DockerHub ID? I tried `TMiguelT` but it didn't like it.

**Comment by TMiguelT** [comment]
Ah, try again now.

**Comment by ewels** [comment]
`tmiguelt` - lower case 🙈

**Comment by TMiguelT** [comment]
Ah yes they force all the usernames to be lowercase for some reason. Thanks!
