### ISSUE TITLE
psycopg2 module not found

### ISSUE THREAD

**Issue by anoronh4** [ewels/MegaQC#126]
I am trying out the megaQC docker on my local machine (Mac) and after executing the following:
`docker run -p 80:80 ewels/megaqc:latest`
I got the error
`ModuleNotFoundError: No module named 'psycopg2'`

I tried a few different versions of the docker to no avail. I also noticed that in `setup.py`, that `psycopg2` is mentioned so my guess is that i shouldn't need it locally installed. maybe psycopg2 should be in `install_requires`?

**Comment by TMiguelT** [comment]
Ah yep that's a recent bug, should be fixed promptly with the introduction of the docker-compose file.
