### ISSUE TITLE
Limiting account creation

### ISSUE THREAD

**Issue by TMiguelT** [ewels/MegaQC#138]
Currently I think it's possible to create an account and then start viewing data without requiring any authorisation. However it's reasonable that users might want new account creation to be subject to approval. 

Considering this, I think the simplest solution would be to have a config setting (do we even have a config file?), or environment variable that enables "strict mode". Under this mode, the admin has to approve new accounts before they can actually log in, but the registration process is the same as usual.

Thoughts?

**Comment by TMiguelT** [comment]
Ah, it seems we have a `MEGAQC_CONFIG` environment variable that can point to a config file. Perfect!

**Comment by ewels** [comment]
Agreed, and I think that this should be on by default. At one point MegaQC had about two or three different config setups in parallel 🙈 There was one copying how MultiQC works, one from Flask etc. Maybe we got around to consolidating these though?

**Comment by ewels** [comment]
And maybe just call it `user_registration_approval` or something instead of strict mode? As I don't think that it's that strict 😅

**Comment by TMiguelT** [comment]
Sounds good to me!
