### ISSUE TITLE
Filter fine tuning

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MegaQC#148]
**Is your feature request related to a problem? Please describe.**

Putting under feature request template, since that seems more accurate than "bug". The filters on the new trend page are working quite well overall, but there are a few tweaks that I think would be good.

**Describe the solution you would like**

1. When creating a new filter, all data fields should be shown
2. The list of fields to use in a filter or a trend plot should be sorted
3. Have a case insensitive "contains" as a filter operation
4. Ability to use existing filters as a subfilter

**Additional context**

1. This only affects `data_types` in practice, as the `meta_types` and `filter_groups` generally have less than the default max results per page (30)
2. Easy enough fix: use `key` for sorting `data_types` and `meta_types` and `id` for sorting `filter_groups`
3. Case sensitivity is baked into the flapison/flask-rest-jsonapi that maps `contains`/`startswith`/`endswith` to the sqlalchemy `like` function and nothing is mapped to `ilike`. This is a particular pain point for us. We filter on report title to separate different types of runs (WGS, exome, cancer, etc.), and casing is not always consistent. Using `ilike` would greatly simplify filter creation.
4. Definitely not a v1 requirement (and probably deserves its own issue), but reusing an already-defined filter could also help when creating more complicated filters.

The first two are simple changes to the relevant endpoint calls in `newFilter.js` and `trend.js`, should probably be combined and might be handy for a new person learning how the rest api filtering works.

The third one requires a change in an external package, so might not be necessary for the v1. I do think having an option for case insensitivity would be very useful and should happen eventually, though.

The fourth I think would be cool, but literally just popped into my head as I was writing this all up so not sure if it would be useful feature to other folks.

**Comment by TMiguelT** [comment]
Yep, just hit the field limit issue. This is quite a problem so I'll endeavour to fix ASAP.

**Comment by TMiguelT** [comment]
From what I can tell, the 30-item limit is coming from `flapison`, which enforces pagination. In theory it shouldn't be hard to collect all pages of results when using the client. Really I'd like to PR some automatic pagination into the API client (https://github.com/holidayextras/jsonapi-client) but it, like a lot of these libraries is no longer maintained!

**Comment by tsnowlan** [comment]
Yeah, can just set `{ "page[size]": 0 }` to the `QcApi.find` call to disable paging on the flapison side though

**Comment by TMiguelT** [comment]
Will that work? Also we need to do this everywhere in the frontend.

**Comment by tsnowlan** [comment]
Yep. I've tested `{ "page[size]": 0, sort: "key" }` (`{ "page[size]": 0, sort: "id" }` for the filter_groups) on all the `find` calls and it works perfectly

**Comment by tsnowlan** [comment]
Points 1 and 2 have been addressed by the pagination changes and are working nicely. Additionally, after looking at the code more I found that the `matches` keyword _does_ use `ilike`, so that takes care of point 3. Point 4 really should be its own issue anyway, so I'm marking this closed and will create a new issue for that functionality.

**Comment by multimeric** [comment]
Thanks! I appreciate you following up on this.
