### ISSUE TITLE
React UI cannot authenticate to rest API

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MegaQC#150]
**Describe the bug**

UI on the new react pages isn't rendering now that auth token is being enforced

**To Reproduce**

1. Start megaqc with any command
2. Select: Data Trends, `/trends/`
3. See error: data types are empty, filters are empty. Check dev tools console to see the 403s from the rest_api requests

**Expected behavior**

Form should populate as it did before auth was enforced

**Additional context**

The problem is due to the `useEffect` calls to populate the form being executed before the client has its token set. It worked previously because the token wasn't needed. This is additionally aggravated be cause the call to `rest_api/v1/users/current` is also returning not authorized, and that's how the front end gets the token in the first place.

**Comment by TMiguelT** [comment]
Thanks for the detail. I'll probably have to fix this. Are you logged in when this happens? Because `/users/current` should at least work here.

**Comment by tsnowlan** [comment]
Yep. Logged in fine, but the request still fails. I think the `api_perms` decorator has priority over the `login_required` decorator and that fails before `current_user` can be checked. I think the `current_user` check could be moved into there and then not have multiple levels of auth checking.

**Comment by tsnowlan** [comment]
Actually, looks like `/users/current` is succeeding, but the token isn't in the client when the other requests fire. Checking `current_user` for on all requests would still fix those, and then the token would be used normally on the API calls after the initial form population.

Another option would be to delay the frontend requests / page load until the client has the `auth_token` populated, but not sure the best way to do that. The `admin` page loads okay. The only `useEffect` there is setting the auth token though, everything else happens afterwards.
