### ISSUE TITLE
Python dependency updates / changes

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MegaQC#151]
**Is your feature request related to a problem? Please describe.**

In addition to the general dependabot stuff, I have these in a list of upgrades that I thought should happen sooner rather than later:

* `argon2-cffi`: the version used is pretty old with weak default hash settings. It also can't parse the `argon2$id` format, so login will fail if the password hash was generated outside MegaQC with a newer version of the package. Probably a pretty rare edge case, but ask me how I know :grin: 
* `psycopg2`: switch to `psycopg2-binary`, since postgres doesn't live in the container anymore
* `click`: a fair bit has changed since v5, though I don't recall specifically why I wanted it upgraded

**Describe the solution you would like**

Modify `setup.py` to use more recent versions of those packages, either specifically or as part of a bigger, overall dependency upgrade. And a bit more weight into finding a nice dependency upgrade/management solution.

**Comment by Zethson** [comment]
> And a bit more weight into finding a nice dependency upgrade/management solution.

Dependabot tracks these usually.

I'll write up a dependabot config, which may require us to move the dependencies from setup.py into requirements.txt files

**Comment by Zethson** [comment]
Closed with https://github.com/ewels/MegaQC/pull/157

Dependabot is already angrily opening PRs
