### ISSUE TITLE
Naive setup questions

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#169]
Hi,

this issue serves me to ask naive setup questions.
The answers to my naive questions should eventually be added into the docs (which I will do!). 
I hope that I do not annoy you, but when I have the "dumb" questions, someone else might too :)

1. Is it best practices to pretty much force the user to allow megaqc to create and initialize the postgres database? Is this permitted in large database clusters? I got an error when I tried to access my own created "megaqc" postgres database.

2. Is it required to change the password of the megaqc user for the postgres DB? The default password is ```megaqcpswd```. I would assume so, but it wasn't part of the instructions.

3. Now something more weird (to me). I followed the installation-production instructions. I created a postgres DB with `megaqc initdb`. No errors. I created my own user and added my token to my config file. Next, I uploaded some data.
This is where things get interesting (for me):
The data is uploaded like this:
```
This is MegaQC v0.3.0

 * Environment: test
 * Database type: sqlite
 * Database path: sqlite:////tmp/tmpi2fw9ngo/megaqc.db
[INFO   ]        commands : Uploading file './HG00097/HG00097.unmapped.SOLID.bfast.GBR.low_coverage.20101123/multiqc_data/multiqc_data.json'
[INFO   ]          megaqc : Data upload queued successfully
```

Why does it create a temporary sqlite db for every upload? Is this intended?
The data is uploaded correctly and accessible as usual and everything works.

Inside the postgres database:
```
megaqc=# \dt
               List of relations
 Schema |        Name         | Type  | Owner  
--------+---------------------+-------+--------
 public | alembic_version     | table | megaqc
 public | dashboard           | table | megaqc
 public | plot_category       | table | megaqc
 public | plot_config         | table | megaqc
 public | plot_data           | table | megaqc
 public | plot_favourite      | table | megaqc
 public | report              | table | megaqc
 public | report_meta         | table | megaqc
 public | roles               | table | megaqc
 public | sample              | table | megaqc
 public | sample_data         | table | megaqc
 public | sample_data_type    | table | megaqc
 public | sample_filter       | table | megaqc
 public | uploads             | table | megaqc
 public | user_plotconfig_map | table | megaqc
 public | user_sampletype_map | table | megaqc
 public | users               | table | megaqc
(17 rows)
```
So yeah, looks good to me.

Again, happy to improve the documentation if my questions are valid.
Thanks!

**Comment by TMiguelT** [comment]
> Is it best practices to pretty much force the user to allow megaqc to create and initialize the postgres database? Is this permitted in large database clusters? I got an error when I tried to access my own created "megaqc" postgres database.

Most of the time I do this in cloud or docker where obviously you can create databases yourself. In a shared DBMS situation I think the sysadmins would assign you a database and you can populate it. In that situation I think you could just set the database name in the MegaQC config and run `initdb` as usual, but it wouldn't create the database because it already exists.

> Is it required to change the password of the megaqc user for the postgres DB? The default password is megaqcpswd. I would assume so, but it wasn't part of the instructions.

It's strongly advised, but the odds are that the database isn't publicly accessible anyway so the connection details aren't massively important.

> Why does it create a temporary sqlite db for every upload? Is this intended?

This relates to the messy config, #96. The reason this happens is because you haven't set the environment variables that trigger either the dev or the prod config, so it defaults to the test config, which creates a random, temporary DB each time. In reality I think you want to use the dev config which you trigger with `FLASK_DEBUG=1`. I suspect the best solution here is to make the dev config the default instead of the test config. This will avoid similar issues in the future.

**Comment by Zethson** [comment]
> Most of the time I do this in cloud or docker where obviously you can create databases yourself. In a shared DBMS situation I think the sysadmins would assign you a database and you can populate it. In that situation I think you could just set the database name in the MegaQC config and run `initdb` as usual, but it wouldn't create the database because it already exists.

I'll have to verify this again, because I since I ran into an issue where the database was available, but it errored out with a stack trace. Maybe because the user did not exist or something.

> This relates to the messy config, #96. The reason this happens is because you haven't set the environment variables that trigger either the dev or the prod config, so it defaults to the test config, which creates a random, temporary DB each time. In reality I think you want to use the dev config which you trigger with `FLASK_DEBUG=1`. I suspect the best solution here is to make the dev config the default instead of the test config. This will avoid similar issues in the future.

Yeah, I checked the configs. My mistake was that I forgot to export the `MEGAQC_PRODUCTION=1` also in my other terminal windows besides the one running `megaqc`
