### ISSUE TITLE
Add megaqc artifacts to .gitignore for docs workflow

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#172]
We are building MegaQC for the Click and Flask docs.
However, then we also commit the build artifacts. The workflow should just add them to the .gitignore (via echo or something).

**Comment by TMiguelT** [comment]
What build artifacts are you concerned about?

**Comment by Zethson** [comment]
pycache, egg files etc.

They don't interfere with the docs building, but they just should not be on the gh-pages branch :)

**Comment by TMiguelT** [comment]
But if you're only publishing the `build/html` directory, why would you be including these files in the `gh-pages` branch?

**Comment by Zethson** [comment]
May have been an issue with my previous setup. Anyways - LGTM
