### ISSUE TITLE
build docs workflow fails at subsequent doc builds and pushes 

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#174]
```
To https://github.com/ewels/MegaQC.git
 ! [rejected]        HEAD -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/ewels/MegaQC.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
```

I honestly cannot reproduce it locally. 
The solution is obvious, but I am not sure why this is happening in the first place.

**Comment by TMiguelT** [comment]
Honestly I think most people just force push to the `gh-pages` branch because they don't care about the history. Check out one of the actions that simplify this process. e.g. the one I use: https://github.com/marketplace/actions/github-pages-action.

**Comment by Zethson** [comment]
@TMiguelT Awesome. Thank you for the hint. 
Workflow is much simpler now.
