### ISSUE TITLE
Add a docs badge to README and 

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#175]
We now have our fancy docs

https://ewels.github.io/MegaQC/

Let's clean up the README a little bit and add a badge for the docs.

**Comment by TMiguelT** [comment]
We also need to add a link to the documentation as the project's website (ie the link at the top of the repo), which is a job for @ewels as the repo admin.

**Comment by TMiguelT** [comment]
Oh, btw I think you broke the link to the screenshot on the readme page
![image](https://user-images.githubusercontent.com/5019367/99868060-447d5f80-2c13-11eb-9716-f246a6b4c1d2.png)

**Comment by Zethson** [comment]
> Oh, btw I think you broke the link to the screenshot on the readme page
> ![image](https://user-images.githubusercontent.com/5019367/99868060-447d5f80-2c13-11eb-9716-f246a6b4c1d2.png)

Thanks. Fixed.

**Comment by Zethson** [comment]
https://github.com/ewels/MegaQC/commit/1833617a997c4ca8089d188235c96c50d8749fc7
