### ISSUE TITLE
Add a fancy landing page, move docs to /docs and add a custom URL

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#176]
I had a discussion with @ewels yesterday and if I understood correctly the plan is as follows:

- [x] Add a fancy custom html page as a landing page. Implementation help: https://github.com/ofosos/sphinx-landing-template
    ```html
    <!-- If we want to have the RTD controls we can 
        {% extends "layout.html" %} -->
    ```
- [x] The landing page has a button which links to /docs
- [x] `/docs/index.html` has the toctree, which is the landing page of the current documentation.
- [x] Add a custom URL to our setup such as https://megaqc.info

I will take care of the technical setup.
@ewels offered to make it pretty and to add the custom URL.

**Comment by Zethson** [comment]
PR merged, just waiting for the custom URL now.

**Comment by ewels** [comment]
Working on this now.

Could we please have a `requirements.txt` file and some docs on how to generate the docs locally? I just fudged my way through it adding one package at a time and it was a bit of a faff.. 😁

**Comment by Zethson** [comment]
https://github.com/ewels/MegaQC/blob/master/docs/requirements.txt

**Comment by TMiguelT** [comment]
Oh. I would rather that be in the `setup.py` as a `docs` "extra" (like dev and prod). Instructions would be good though.

**Comment by Zethson** [comment]
The current location is the "common way" though. e.g. RTD always looks for the file there.

**Comment by TMiguelT** [comment]
Hmm okay if there's a convention behind this then that's probably better.

**Comment by Zethson** [comment]
I will add instructions, but for now you can follow:
https://github.com/ewels/MegaQC/blob/master/.github/workflows/publish_docs.yaml

**Comment by ewels** [comment]
> https://github.com/ewels/MegaQC/blob/master/docs/requirements.txt

How did I not see this 🤦🏻  Sorry! It was right in front of me!

**Comment by ewels** [comment]
Ok, custom domain set up and working: http://megaqc.info/ ✅ 

I pushed a commit 259a272befe70d6b9f6ad7abea3b7ba91cfa5797 to master without PR by the way, sorry - was small and I was trying to be speedy..

**Comment by ewels** [comment]
Side note: is there any way we can get the `View page source` link to point to GitHub instead of, for example, http://megaqc.info/_sources/docs/installation/installation.rst.txt ?

**Comment by ewels** [comment]
Not closed yet as I still need to sort out the homepage.

**Comment by Zethson** [comment]
> Not closed yet as I still need to sort out the homepage.

Oops :)

**Comment by ewels** [comment]
Two other things:

- Would also be nice if the homepage link in the top of the sidebar pointed to the root domain URL instead of the docs root.
- Do we need the readme shown at http://megaqc.info/docs/readme.html ? I'm not sure that it really adds much. Personally I would prefer to revert the repo readme back to how it was (markdown) and omit it from the docs website.

**Comment by Zethson** [comment]
@ewels let's collect your feedback and discuss it here: https://github.com/ewels/MegaQC/issues/217

**Comment by ewels** [comment]
Ok, and HTTPS now working / enforced 🔒 ✅
