### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#196]
**Is your feature request related to a problem? Please describe.**

Whenever I set up a MegaQC instance I need to populate it with some data.
However, there is no example data in the MegaQC repository. Hence, I always resort to https://github.com/TMiguelT/1000gFastqc .
This repository however is outside of the MegaQC repository scope and contains data, which may not work with the comparisons plot.

**Describe the solution you would like**

Maybe the MegaQC repository itself should contain some (say 5?) example reports, which could be used for development and testing purposes. The data should support all features.
Additionally, there should be a small shell script, which uploads all reports.

**Comment by Zethson** [comment]
@TMiguelT Would it be fine for you if I add a subset of your data with an upload script to this repository?

**Comment by tsnowlan** [comment]
There is also this repo: https://github.com/ewels/MultiQC_TestData

It's not updated too often, but it's used in the MultiQC tests so should relevant here.

**Comment by Zethson** [comment]
@tsnowlan yeah I am aware of it.
However, it has test data per module, which in my opinion is not that useful for users trying out MegaQC or developers trying to test a nice mix of data.

**Comment by TMiguelT** [comment]
Actually I'm working on a new test data set which will have 4 modules and 100s of samples. So you can feel free to wait for me to address this.

**Comment by TMiguelT** [comment]
The new data is located here: https://github.com/TMiguelT/1000g-megaqc. However I'm having some issues when I try to load them all into MegaQC, which I will look into. The reports that do successfully upload are helpful for testing, however.
