### ISSUE TITLE
Minor doc improvements

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#217]
- [x] Add instructions on how to build and view the documentation locally
- [x] Evaluate whether there is any way we can get the View page source link to point to GitHub instead of, for example, http://megaqc.info/_sources/docs/installation/installation.rst.txt 
- [x] Would also be nice if the homepage link in the top of the sidebar pointed to the root domain URL instead of the docs root.
- [x] Discuss whether want to show the README at all and revert it back to markdown
- [x] Changelog is far to hidden. It can even go into the root in my opinion.

**Comment by Zethson** [comment]
@ewels  We can omit the README from the documentation, no problem. I don't see the point in reverting it to markdown for consistency reasons, but if you feel more comfortable with it that ain't a problem.

**Comment by ewels** [comment]
No big reason - I just dislike reading / writing RST 😅 I'm doing a bunch of sphinx stuff for @nf-core at the moment though, so maybe I will start to actually learn how to write it!
