### ISSUE TITLE
Question about MegaQC Docker installation

### ISSUE THREAD

**Issue by chrispyatt** [ewels/MegaQC#309]
**Question**

Hi, I'm a bit confused as to how to set MegaQC up using Docker. The docs (https://megaqc.info/docs/installation/installation.html#docker) suggest that getting things going should be fairly painless but having run the command (docker run -p 80:80 ewels/megaqc) all I get is an error: 

`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
    Is the server running on host "127.0.0.1" and accepting TCP/IP connections on port 5432?`

I'm not particularly familiar with Docker in general so I thought I'd ask whether I'm missing any steps not mentioned in the docs. It does mention publishing the port but I'm not sure what this refers to and whether it's the cause of the error.

Best wishes,
Chris

**Comment by multimeric** [comment]
So if you use the first option, of the single container, you need to have a database server hosted somewhere else that it can connect to. If you're starting from scratch and don't already have a database running, I instead recommend the second option: the docker compose stack. This will pull down and start a database server for you, in a container.

**Comment by chrispyatt** [comment]
Follow up. This now works a treat. Is there a way to package it so that it doesn't need to pull from the web? I.e. so I can set up on a server that lacks a direct internet connection. I presume I can save the various images pulled and then modify a config(?) to point to those instead of the web somehow?

**Comment by multimeric** [comment]
Yes you can certainly do this. I'm not sure of the best method but you could for example [`docker image save`](https://docs.docker.com/engine/reference/commandline/image_save/) each of the constituent images. It would probably be easiest to build the stack on a machine with internet access, then save to disk the specific images downloaded by that machine.
