### ISSUE TITLE
Better app logging

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MegaQC#41]
Visible logging is currently just access log type info (get, post, 4xx, 5xx, etc.). No errors printed when, e.g., a file sent from multiqc could not be inserted. Makes it difficult to track down where the issues are happening.

`Flask.app.logger` should be accessible everywhere, but doesn't seem to be writing to console currently. I think this is just a config flag somewhere, or maybe setting a log file location?

**Comment by ewels** [comment]
Yes, I've noticed the same - that it works sporadically at least. I have a bunch of lazy `print()` statements for this reason as I haven't got around to looking into it yet.

**Comment by tsnowlan** [comment]
This should be fixed now with the `logger.logLevel` updates in #51 . Logs can be added with `Flask.app.logger.{DEBUG,INFO,WARN,ERROR}` or `Flask.current_app.logger.{DEBUG,INFO,WARN,ERROR}`, depending on where in the code you are.

**Comment by tsnowlan** [comment]
Nope, still missing logs in production env.

**Comment by tsnowlan** [comment]
Gonna re-close, since this was re-fixed with #57 .
