### ISSUE TITLE
Edit filters - edit broken

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MegaQC#55]
When clicking on the Edit button of an existing filter, it brings up the new filter modal. Is there an edit modal that it should be pointed to instead, or was the plan to populate the new filter modal with existing values and an `update` instead of `create` button?

**Comment by ewels** [comment]
I suspect that the plan was to populate the existing modal. That's what I've done elsewhere...

**Comment by TMiguelT** [comment]
Closing, as this should have been fixed in the React rewrite. If not, I will re-open.
