### ISSUE TITLE
Check that DB exists and exit early with nice warning

### ISSUE THREAD

**Issue by ewels** [ewels/MegaQC#69]
At the moment, if the database hasn't been initialised, you get a massive traceback when trying to load a page (see #67). It would be nicer to check this when we first load, and exit with an error.

I've been playing with this this evening and got as far as this snippet, which basically does the job:

```python
# Attempt to connect to the database exists to check that it exists
try:
    dbengine = sqlalchemy.create_engine(CONFIG.SQLALCHEMY_DATABASE_URI).connect()
    metadata = sqlalchemy.MetaData(dbengine, reflect=True)
    assert 'sample_data' in metadata.tables
except:
    print("\n##### ERROR! Could not find table 'sample_data' in database!")
    print("Has the database been initialised? If not, please run 'megaqc initdb' first")
    print("Exiting...\n")
    sys.exit(1)
else:
    dbengine.close()
```

However, I can't for the life of me figure out _where_  to put it. I've tried a few places, but then it stops you from running `megaqc initdb`. In other places it runs on workers, so doesn't actually kill the main server.

Any ideas @tsnowlan / @Galithil?

**Comment by tsnowlan** [comment]
My first thought is to make a function that is essentially that snippet, and then figure out the best place(s) to call it. Maybe after app creation in `wsgi.py` and after the command line processing. That way can skip if `initdb` or `help` are used but still catch it with `megaqc run` or if it's being run behind gunicorn.

**Comment by TMiguelT** [comment]
The quickest fix for this is to mention the `initdb` command in the documentation, because a lot of it tells you to `megaqc run` immediately after installing, e.g. https://github.com/ewels/MegaQC/blob/master/README.md#testing-megaqc

**Comment by Zethson** [comment]
Maybe we can use the [click context](https://click.palletsprojects.com/en/7.x/complex/#contexts) to special handle commands like `megaqc initdb` for which we would like to skip this check?

**Comment by Zethson** [comment]
What I assume could work is to add a custom class to the group and overwrite get_command to special treat functions like discussed above.
Reference from cookietemple: https://github.com/cookiejar/cookietemple/blob/master/cookietemple/custom_cli/click.py#L108

**Comment by Zethson** [comment]
```
@click.group(cls=FlaskGroup, create_app=create_megaqc_app)
@click.pass_context
def cli(ctx):
    """
    Welcome to the MegaQC command line interface.

    \nSee below for the available commands - for example,
    to start the MegaQC server, use the command: megaqc run
    """
    # Attempt to connect to the database exists to check that it exists
    if ctx.invoked_subcommand != 'initdb':
        try:
            dbengine = sqlalchemy.create_engine(CONFIG.SQLALCHEMY_DATABASE_URI_SAN).connect()
            metadata = sqlalchemy.MetaData(dbengine, reflect=True)
        except Exception as e:
            print(e)
            print("\n##### ERROR! Could not find table 'sample_data' in database!")
            print("Has the database been initialised? If not, please run 'megaqc initdb' first")
            print("Exiting...\n")
            sys.exit(1)
        else:
            dbengine.close()
```

Like this we can run the function only when the command is not `initdb`, but the issue here is that CONFIG has not been set yet.
The complete code in cli runs before `create_app` is called.
