### ISSUE TITLE
Trouble in getting megaqc upload function to work 

### ISSUE THREAD

**Issue by skanwal** [ewels/MegaQC#72]
Hi Phil,

I am testing the `megaqc upload` function (locally on my laptop) to get data into megaQC server.

I installed both megaQC and multiQC in the same environment, as below:
```bash
$ which megaqc
/Users/kanwals/miniconda3/envs/multiqc/bin/megaqc

$ which multiqc 
/Users/kanwals/miniconda3/envs/multiqc/bin/multiqc
```
I am getting the following error when running megaqc upload:

```
$ megaqc upload multiqc_data/multiqc_data.json

This is MegaQC v0.1.dev1

Env: test
 * Database type: sqlite
 * Database path: sqlite:////Users/kanwals/miniconda3/lib/python3.6/site-packages/test.db
Error - This function requires MultiQC to be installed
```
For testing, I ran multiqc on a sample, and the report was successfully posted to megaqc server. It's only the `megaqc upload` function that is throwing an error.

Any help will be appreciated.

Regards,
Sehrish

**Comment by ewels** [comment]
This error is triggered when trying to import `multiqc` here:
https://github.com/ewels/MegaQC/blob/42f7718f7a819acb496d9a74eb020badf7969eda/megaqc/commands.py#L173-L178

Now that we're sure that both packages are installed in the same conda environment, my next guess is that it's something to do with _how_ they're installed.

For example, see this SO post: https://stackoverflow.com/a/34797806/713980 where combinations of installing with and without `sudo` caused problems. Or something to do with the Python path... 

How exactly did you install both packages?

**Comment by skanwal** [comment]
Thanks for the response, Phil.

I did check the `ImportError` in `commands.py` that was triggering the issue. That's when I thought of testing `multiqc.utils import config as multiqc_config` on python interpreter inside the conda environment (which worked fine).

**How exactly did you install both packages?**

I followed the following steps.

- Created a new conda environment. 
  `conda create --name multiqc`

- Installed multiqc using `conda install -c bioconda multiqc`
```
$ which pip
/Users/kanwals/miniconda3/envs/multiqc/bin/pip
$ which python
/Users/kanwals/miniconda3/envs/multiqc/bin/python
$ /Users/kanwals/miniconda3/envs/multiqc/bin/python --version
Python 3.6.8 :: Anaconda, Inc.
```
- Installed megaqc using `pip install megaqc` in the same `multiqc` conda environment (I didn't use sudo in the command).

As in the snippet above, the pip path looks okay - and the python version as well, _I guess_. 

Now the only point I can think of at this moment is using `conda` for multiqc and `pip` for megaqc installation.
Not sure, if this could be the issue, though you had mentioned in gitter that "Pip installs within a conda environment should be fine".

Happy to further debug and provide more info, if needed.

**Comment by tsnowlan** [comment]
I'm having some trouble replicating this. Are you using the latest version of conda? Does `which multiqc` and `which megaqc` show both executables in the same environment?

When I attempt to install multiqc via `conda install -c bioconda multiqc` the recipe includes a downgrade to python 2.7. Megaqc works with 2.7, it's odd that you're still showing python v3.6.8 after installing multiqc in that environment. I'm also not sure if a MegaQC running on py3 would be able to access the source for a py2 MultiQC install.

**Comment by skanwal** [comment]
Yes, I have a fairly recent conda version `4.6.8`

And I have an update as well. 

- I started again from scratch i.e. created anew conda environment. Used `pip` for both multiqc and meagaqc installation.

```
$ which megaqc
/Users/Kanwals/miniconda3/bin//megaqc
$ which multiqc
/Users/Kanwals/miniconda3/bin//multiqc
$ which python
/Users/Kanwals/miniconda3/bin//python
$ /Users/Kanwals/miniconda3/bin//python --version
Python 3.6.4 :: Anaconda, Inc.
```

- Updated identification token in `~/.multiqc_config.yaml` 
- Ran megaqc upload and it worked (yay!) 

```
$ megaqc upload ./multiqc_data/multiqc_data.json
This is MegaQC v0.1.dev1

Env: test
 * Database type: sqlite
 * Database path: sqlite:////Users/kanwals/miniconda3/lib/python3.6/site-packages/test.db
[INFO   ]        commands : Uploading file './multiqc_data/multiqc_data.json'
[INFO   ]          megaqc : Data upload queued successfully
```

A couple _other_ comments:
- Before trying pip in a fresh conda environment, I tried conda for installing both megaqc and multiqc. 
   - `conda install -c bioconda multiqc` works fine. However, you mentioned that the recipe includes a downgrade to python 2.7. It didn't in this case, as the python version after installation was 3.6
   ```
   $ which python
   /Users/kanwals/miniconda3/envs/mqc/bin/python
   (mqc) 4180L-137952-M ~/Documents/UMCCR/git/RNA-seq-analysis/readcount-analysis $ python -- 
  version
   Python 3.6.8 :: Anaconda, Inc.
   ```

   - Megaqc installation via conda does not work for me. I tried various things (such as updating channel preferences in `.condarc`)
   ```
   $ conda config --get channels
   --add channels 'defaults'   # lowest priority
   --add channels 'conda-forge'
   --add channels 'bioconda'   # highest priority
   ```

   But I still got:
   ```
   $ conda install -c bioconda megaqc
   Collecting package metadata: done
   Solving environment: failed

   PackagesNotFoundError: The following packages are not available from current channels:

    - megaqc

   Current channels:

    - https://conda.anaconda.org/bioconda/osx-64
    - https://conda.anaconda.org/bioconda/noarch
    - https://conda.anaconda.org/conda-forge/osx-64
    - https://conda.anaconda.org/conda-forge/noarch
    - https://repo.anaconda.com/pkgs/main/osx-64
    - https://repo.anaconda.com/pkgs/main/noarch
    - https://repo.anaconda.com/pkgs/free/osx-64
    - https://repo.anaconda.com/pkgs/free/noarch
    - https://repo.anaconda.com/pkgs/r/osx-64
    - https://repo.anaconda.com/pkgs/r/noarch

   To search for alternate channels that may provide the conda package you’re
   looking for, navigate to

      https://anaconda.org

   and use the search bar at the top of the page.
   ```

Sorry about the long comment, but thought it might help others who may hit the same issue.

**Comment by ewels** [comment]
Ok great - glad you got it working, and thanks for the feedback!

> MegaQC installation via conda does not work for me

This is expected - MegaQC does not have any stable releases and has not been packaged in bioconda yet, as MultiQC has.

Phil
