### ISSUE TITLE
Sample summary page

### ISSUE THREAD

**Issue by TMiguelT** [ewels/MegaQC#76]
Is there a page that will just simply list the samples in the database, maybe with a date and name associated with each? Currently I'm struggling to quickly work out what data is in my megaQC instance.

**Comment by skanwal** [comment]
MegaQC `edit_reports` section might help - but supposition here would be there is one multiQC report per sample. 
Probably you're more interested in having sample names with the report `creation_date` probably in `title`?

**Comment by TMiguelT** [comment]
Yes unfortunately I have multiple samples per report. However this is still a useful page to know about! I think if samples were listed on this page, it would solve this need.

**Comment by TMiguelT** [comment]
Solved by #99
