### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ohofmann** [ewels/MegaQC#8]
Phil,

trying to find ways to better debug this. Uploading a MultiQC report (either directly with `megaqc upload` or through an existing file list) results in:

```python
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/megaqc/public/views.py", line 32, in home
    num_samples = get_samples(count=True),
  File "/usr/local/lib/python2.7/site-packages/megaqc/api/utils.py", line 517, in get_samples
    return sample_query.one()[0]
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2719, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2790, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2813, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: sample [SQL: u'SELECT count(DISTINCT sample.sample_name) AS count_1 \nFROM sample']
```

What information can I provide you with to reproduce this? Just the `JSON`?

**Comment by ewels** [comment]
Hi @ohofmann,

Looks like your database hasn't been initialised properly (`no such table`). Have you run `megaqc initdb`?

Phil

**Comment by ohofmann** [comment]
Yep!

```$ megaqc initdb
This is MegaQC v0.1.dev0

/usr/local/lib/python2.7/site-packages/test.db
Initialized the database.

$ megaqc run
This is MegaQC v0.1.dev0

/usr/local/lib/python2.7/site-packages/test.db
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

Followed by:

```
$ multiqc -l 2017-11-12_mb_workflow/multiqc/list_files_final.txt -c 2017-11-12_mb_workflow/multiqc/multiqc_config.yaml
[INFO   ]         multiqc : This is MultiQC v1.3
[INFO   ]         multiqc : Template    : default
Searching 40 files..  [####################################]  100%             
[INFO   ]        samtools : Found 2 stats reports
[INFO   ]        samtools : Found 2 idxstats reports
[INFO   ] goleft_indexcov : Found goleft indexcov ROC reports for 2 samples
[INFO   ] goleft_indexcov : Found goleft indexcov bin reports for 2 samples
[INFO   ]        bcftools : Found 1 stats reports
[INFO   ]        bcftools : Found 1 stats reports
[INFO   ]          fastqc : Found 2 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]          megaqc : Sending data to MegaQC
[ERROR  ]          megaqc : Error: JSON response could not be parsed (status code: 200)
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
oho@Olivers-iMac:~/Downloads/MultiQC/Benchmark$ multiqc -l 2017-11-12_mb_workflow/multiqc/list_files_final.txt -c 2017-11-12_mb_workflow/multiqc/multiqc_config.yaml
[INFO   ]         multiqc : This is MultiQC v1.3
[INFO   ]         multiqc : Template    : default
Searching 40 files..  [####################################]  100%             
[INFO   ]        samtools : Found 2 stats reports
[INFO   ]        samtools : Found 2 idxstats reports
[INFO   ] goleft_indexcov : Found goleft indexcov ROC reports for 2 samples
[INFO   ] goleft_indexcov : Found goleft indexcov bin reports for 2 samples
[INFO   ]        bcftools : Found 1 stats reports
[INFO   ]        bcftools : Found 1 stats reports
[INFO   ]          fastqc : Found 2 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]          megaqc : Sending data to MegaQC
[ERROR  ]          megaqc : Error: JSON response could not be parsed (status code: 200)
```

**Comment by ohofmann** [comment]
Website is up and running with debug/flask side window active; it just doesn't show any samples. Alright, let me try and reproduce this on another machine first and with data from a different run.

**Comment by ewels** [comment]
Can you try looking into the SQLite database file directly? Something like this:

```
$ sqlite3 dev.db
SQLite version 3.13.0 2016-05-18 10:57:30
Enter ".help" for usage hints.

sqlite> .databases
seq  name             file
---  ---------------  ----------------------------------------------------------
0    main             /Users/philewels/GitHub/MegaQC/dev.db

sqlite> .tables
plot_category        roles                uploads
plot_config          sample               user_plotconfig_map
plot_data            sample_data          user_sampletype_map
report               sample_data_type     users
report_meta          sample_filter

sqlite> .dump sample
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE sample (
	sample_id INTEGER NOT NULL,
	sample_name VARCHAR(80),
	report_id INTEGER,
	PRIMARY KEY (sample_id),
	FOREIGN KEY(report_id) REFERENCES report (report_id)
);
COMMIT;
```

**Comment by ewels** [comment]
Hi @ohofmann! Did you get any further with this? It makes me nervous as the back-end database stuff is the bit that I had hoped was more "finished" than the rest... 😉 

Phil

**Comment by ohofmann** [comment]
Haha. No, sorry, it’s been somewhat low priority as we fix / implement basic infrastructure right now. Ill ask Vlad to tackle this in the new year, promise.

Best, Oliver

--
@fiamh
Skype: ohofmann
+61 466 366 501

**Comment by ewels** [comment]
Ok cool - no rush at all! As long as you’re not silently struggling and discarding MegaQC to the rubbish tip.. ;) We’re hiring lots of people at the moment so I hope to be able to put someone on the project properly in the new year.

**Comment by NMNS93** [comment]
Hi Phil, 

Attempted to run MegaQC yesterday and ran into the same error as above after 
`megaqc upload <multiqc_json>`:
[ERROR  ]          megaqc : Error: JSON response could not be parsed (status code: 400)

The console log showed an empty POST request, am I right in assuming this should have the json data?:
127.0.0.1 - - [18/Apr/2018 08:40:55] "POST / HTTP/1.1" 200 -

Here you can find files for my [setup, localserver and sqlite3 outputs](https://gist.github.com/NMNS93/09aeeb88004307c3a3dc3744052196a4). Let me know if any more info will help. 

Best,
Nana

**Comment by ewels** [comment]
Hi Nana,

Thanks for the fantastic set and work notes - those are extremely useful (if nothing else, to see the teething issues that you had during the install).

I don't think that your error is the same as the above one (no large stack trace error), but it does trigger a similar warning about the JSON code not being parsed.

I think that your problem is due to [this step](https://gist.github.com/NMNS93/09aeeb88004307c3a3dc3744052196a4#file-megaqc_setup-txt-L37):

```
## FIX: Edit the config in '/py2env/lib/python2.7/site-packages/multiqc/utils/config_defaults.yaml', change 'megaqc_url = None' to 'megaqc_url = "http://127.0.0.1:5000/"'
```

This `megaqc_url` should be `http://127.0.0.1:5000/api/upload_data`

Instead of setting this manually, the idea is that you log into MegaQC and navigate to "MultiQC Configuration" (http://127.0.0.1:5000/users/multiqc_config). This page has instructions and some YAML that you can copy to a MultiQC config file (also including an authentication key).

I need to write documentation and tutorials to describe all of this stuff instead of forcing people to try to figure it out for themselves, sorry that it's not been very easy so far. I may also look into whether I can get the server to detect the MultiQC API request headers and give a more useful error if there's something wrong with the URL.

Let me know how you get on...

Phil

**Comment by Galithil** [comment]
@ohofmann  : 
Can you run `mkdir /usr/local/lib/python2.7/site-packages/megaqc/uploads/` and try again ?

@NMNS93 : 
Can you run `mkdir /home/nana/Documents/megaqc/py2env/local/lib/python2.7/site-packages/megaqc-0.1.dev0-py2.7.egg/megaqc/uploads` and try again ? 

@ewels on a setup.py install, it looks like the uploads folder is not created properly, so uploads are not possible. On top of that, the error is not catched properly and not returned, cauing the JSON issue in the end.

**Comment by ewels** [comment]
Addressed in https://github.com/ewels/MegaQC/commit/7d70c2aa10f2844602b0c8d44c484015f179f9ea

**Comment by ewels** [comment]
Addressed in https://github.com/ewels/MegaQC/commit/fe1cd81be266108806adb8127e917c25b4d79da1

**Comment by NMNS93** [comment]
Hi @ewels and @Galithil,

Please ignore this if already addressed by the recent commit: Running the mkdir command above didn't seem to work at first but it actually expected 'uploads' to be one directory up as so,

`mkdir /home/nana/Documents/megaqc/py2env/local/lib/python2.7/site-packages/megaqc-0.1.dev0-py2.7.egg/uploads`

I can now upload my multiqc json files with `megaqc upload`. 
Thanks for the super-speedy responses and will aim to feedback on usage when possible!

-Nana

**Comment by ewels** [comment]
Ok, closing this issue now as I _think_ (hope) that we've resolved the issue. Thanks all!
