### ISSUE TITLE
docker: decouple database

### ISSUE THREAD

**Issue by matthdsm** [ewels/MegaQC#88]
Hi,

What is your stance on decoupling the db from the docker image for MegaQC? Mashing multiple services together in one container kind of goes against the best practices for docker.
Deploying MegaQC in a distributed production environment is not feasible using this strategy.
This also makes plugging other db's and persisting data easier.

Cheers
M

**Comment by matthdsm** [comment]
xref #89

**Comment by TMiguelT** [comment]
Hi @matthdsm. I've also been working on MegaQC a lot lately. I totally agree with the need to do this, it's something I was meaning to get around to myself. So I'll post some comments on your PR.

**Comment by matthdsm** [comment]
Great to hear there's some development going on. I've been looking at your open PR's too. Nice work you're doing there! I'm looking forward to the finished product.

**Comment by tsnowlan** [comment]
Definitely agree the Dockerfile could use some love :+1:

**Comment by ewels** [comment]
Yup - sounds good! I think it's nice having the option to run postgres in a container, as it can be a pain to install, but I'm assuming that you're suggesting having multiple containers running in parallel which would be fine 👍

**Comment by matthdsm** [comment]
That's the idea. By adding a compose file as suggested by @TMiguelT, spinning up a working env is just a `docker-compose up` away and could easily become the preferred method of taking MegaQC for a spin.

M

**Comment by TMiguelT** [comment]
I'm going to close this issue now that #89 is merged, and will track the development of a docker-compose file in #123.
