### ISSUE TITLE
Python version support

### ISSUE THREAD

**Issue by TMiguelT** [ewels/MegaQC#91]
Just wondering if we have some firm rules in terms of what versions of Python we want to support. Can we assume Python 2 is no longer relevant, and I can clean up the 2/3 compatibility stuff in my PRs?

In addition, there are a few libraries I've looked into using, such as https://github.com/Nobatek/flask-rest-api and/or https://github.com/Nobatek/flask-rest-api that are Python 3.5+ only. Perhaps this is too much of a limitation since Python 3.5 was only released in 2015?

**Comment by tsnowlan** [comment]
I am in favor of doing python3+, but that might need to be a call by @ewels. MultiQC is still being used in environments that are only python 2, but I'm not sure that is the same for MegaQC. It might still be in low enough usage that the likelihood of people running in such an outdated environment is low.

**Comment by ewels** [comment]
I think python 3+ is fine now, as long as we’re clear about it. I wanted py2k support when I started the project, but that was a few years ago now. MultiQC may well also go py3k only soon anyway.

**Comment by TMiguelT** [comment]
In my REST API PR (#87), I've been forced to drop Python 2.X and Python <3.5, because a lot of libraries in the Marshmallow world no longer support these versions.
